/*
 * GameScreen Class (Window that shows during gameplay)
 * 
 * Written by  Alex Foley & James Milne for the 
 * ICS4UI Software Design Project
 */

package battleship;

//Class declaration
public class GameScreen extends javax.swing.JFrame {
    
    //GameScreen constructor
    public GameScreen(String difficulty ) {
        //Initialize the GUI stuff
        initComponents();
        
        //Set the big board and small board to be opponents
        this.bigBoard.setOBoard(this.smallBoard);
       
        //Set the AI on the board based on the game's difficulty
        this.bigBoard.setAI(new AI(this.smallBoard, difficulty));
        
        //Set the key bindingd for the big board
        this.bigBoard.setKeyBindings();
        
    }
    
    //Method for drawing the stats on the board
    public void drawStats (){
        //Initialize all of the guesses and hits to 0
        int AIGuesses = 0;
        int userGuesses = 0;
        int numAIHits = 0;
        int numUserHits = 0;
        
        //Loop through all of the squares on the board
        for(int i = 0; i<this.getBigBoard().getBoardSize(); i++){
            for (int j = 0; j<this.getBigBoard().getBoardSize(); j++){
                //If the square is guessed by the user, increment the number of 
                //guesses
                if (this.getBigBoard().isGuessed(i, j)){
                    userGuesses++;
                   //If there is a ship there, increment the number of hits
                   if (this.getBigBoard().isShip(i, j)){
                       numUserHits++;
                   }
                }
                //If the square is guessed by the AI, increment the number of 
                //guesses
                if (this.getSmallBoard().isGuessed(i, j)){
                    AIGuesses++;
                   //If there is a ship there, increment the number of hits
                   if (this.getSmallBoard().isShip(i, j)){
                       numAIHits++;
                   }
                }
            }
        }
        //Update the text to reflect the stats calculated
        this.AIShots.setText("Shots: " + AIGuesses);
        this.userShots.setText("Shots: " + userGuesses);
        this.AIHits.setText("Hits: " + numAIHits);
        this.userHits.setText("Hits: " + numUserHits);
    }
   
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel = new javax.swing.JLabel();
        AILabel = new javax.swing.JLabel();
        userHits = new javax.swing.JLabel();
        AIShots = new javax.swing.JLabel();
        AIHits = new javax.swing.JLabel();
        userShots = new javax.swing.JLabel();
        statsLabel = new javax.swing.JLabel();

        bigBoard = new Board(10, 450, true, this);
        bigBoard.addMouseListener(bigBoard);
        bigBoard.addMouseMotionListener(bigBoard);
        smallBoard = new Board(10, 280, false, this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Battleship");
        setResizable(false);

        org.jdesktop.layout.GroupLayout bigBoardLayout = new org.jdesktop.layout.GroupLayout(bigBoard);
        bigBoard.setLayout(bigBoardLayout);
        bigBoardLayout.setHorizontalGroup(
            bigBoardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 453, Short.MAX_VALUE)
        );
        bigBoardLayout.setVerticalGroup(
            bigBoardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 453, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout smallBoardLayout = new org.jdesktop.layout.GroupLayout(smallBoard);
        smallBoard.setLayout(smallBoardLayout);
        smallBoardLayout.setHorizontalGroup(
            smallBoardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 281, Short.MAX_VALUE)
        );
        smallBoardLayout.setVerticalGroup(
            smallBoardLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 281, Short.MAX_VALUE)
        );

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userLabel.setText("User");

        AILabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AILabel.setText("AI");

        userHits.setText("Hits: 0");

        AIShots.setText("Shots: 0");

        AIHits.setText("Hits: 0");

        userShots.setText("Shots: 0");

        statsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        statsLabel.setText("Statistics");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(bigBoard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 127, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(smallBoard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(userHits, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(userShots, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(userLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(38, 38, 38)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(AILabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(AIShots, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(AIHits, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(statsLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(50, 50, 50)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .add(bigBoard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(smallBoard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(statsLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(userLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(7, 7, 7)
                        .add(AILabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(userHits, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, AIHits, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(userShots, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(AIShots, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Returns the big board on the screen
    public Board getBigBoard() {
        return this.bigBoard;
    }
    
    //Returns the small board on the screen
    public Board getSmallBoard() {
        return this.smallBoard;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AIHits;
    private javax.swing.JLabel AILabel;
    private javax.swing.JLabel AIShots;
    private javax.swing.JLabel statsLabel;
    private Board bigBoard;
    private Board smallBoard;
    private javax.swing.JLabel userHits;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userShots;
    // End of variables declaration//GEN-END:variables

}
